### ISSUE TITLE
KUEHL_RAUMSOLL_TAG temperature is displayed incorrectly

### ISSUE THREAD

**Issue by Nebnenut** [kr0ner/OneESP32ToRuleThemAll#16]
Everything works great, but the temperature is displayed as 250 degrees

![IMG_0548](https://github.com/kr0ner/OneESP32ToRuleThemAll/assets/97184911/b8221374-eb85-4229-9243-f44ff56f53b6)

**Comment by kr0ner** [comment]
Thanks for reporting :) I know the Problem and the fix ist ready. Will test it later and push it 👍🏼 forgot to specify decimal_value types for those temps. By default values are interpreted as integers 😅

**Comment by kr0ner** [comment]
fixed here: https://github.com/kr0ner/OneESP32ToRuleThemAll/commit/6521a009d1d1923e87b524c75f6ba1e2c6552c8c#diff-aa67afd076546b54264d045a7d88dc2d071365cab4440c8a0cd8c08832d60759R103-R105
