### ISSUE TITLE
Switch off LUEFT_STUFE_TAG automatically

### ISSUE THREAD

**Issue by Nebnenut** [kr0ner/OneESP32ToRuleThemAll#18]
I currently have the phenomenon that the LUEFT_STUFE_TAG switches off automatically as soon as the entry "no longer available" is in the log.

The same thing happens when the ESP controller is disconnected from the power and powered again.currently only detectable with the LUEFT_STUFE_TAG sensor.

edit: I have a Stiebel Eltron 5s Plus, which is the same as the THZ 504 on which your Git is based.

![image](https://github.com/user-attachments/assets/98b34ed9-fbc9-4524-a066-4b3da32be128)

**Comment by kr0ner** [comment]
Hi, I have a suspicion: After boot we ask the heat pump for the value of LUEFT_STUFE_TAG ... but we are somehow reading the request and not the response. Requests always have 0 as a value. On reception of zero we turn the fan off ... which might be the second problem. I will try to prepare a fix. 

Side question: why is your esp so often not reachable? :thinking:

**Comment by Nebnenut** [comment]
the problem with the device losing connection has been going on since this morning. If necessary, I'll swap the ESP for another one, of course everyone has a few ESP controllers on reserve at home :-D

**Comment by kr0ner** [comment]
> of course everyone has a few ESP controllers on reserve at home

Yes :) you never know :D

hm ... so it might be caused by my changes from yesterday evening? When did you do the last update?
So it's definitely a bug in the code ... but we should also tackle the resets. If it is reproducible it would be nice to have the log output so that I can check what the last command was and then guess what could've been the problem.

**Comment by Nebnenut** [comment]
Ok, the ESP has problems with the wifi chip or with the WiFi reception. The Fritzbox says cancels registrations. I'll swap it out.


https://pastebin.com/AEt0RfVd

**Comment by kr0ner** [comment]
ok, first thing that I have overlooked 😅 
https://esphome.io/components/fan/#base-fan-configuration
> restore_mode (Optional): Control how the fan attempts to restore state on boot.
> ALWAYS_OFF (Default) - Always initialize the fan as OFF on bootup.
That explains a lot ... but this is only half the story ... once this is fixed, fan speeds behave weird ... still investigating
