### ISSUE TITLE
Fix for negative outside temps

### ISSUE THREAD

**Issue by croessi** [kr0ner/OneESP32ToRuleThemAll#54]
Since it now became cold outside I found out that the type of _value_ should be of std::int16_t instead of std::uint16_t. I changed it locally and worked, but I lack time during next days to rebase and provide pull request. But maybe more users are surprised by 6500°C outside temp ;-)

**Comment by kr0ner** [comment]
worst thing is i fixed it last year already https://github.com/kr0ner/OneESP32ToRuleThemAll/commit/ea75f312bfd643b1f9598e92f9adf424f39265ae ... nice regression 😅
