### ISSUE TITLE
Aussentemperatur sometimes wrong

### ISSUE THREAD

**Issue by skycryer** [kr0ner/OneESP32ToRuleThemAll#62]
Just saw today that outside temp value gone trough the roof with around 6500 celsius showing.

<img width="608" alt="Bildschirmfoto 2024-11-21 um 17 52 11" src="https://github.com/user-attachments/assets/ec732673-393f-43db-aa86-b742db66dee8">

[logs_esphome-web-7d2a20_logs.txt](https://github.com/user-attachments/files/17849458/logs_esphome-web-7d2a20_logs.txt)

Display at heating pump show correct value

![PXL_20241121_170215328](https://github.com/user-attachments/assets/c3ecfefd-43cf-49b0-b18b-24bd17f3e6d0)

**Comment by skycryer** [comment]
[logs_esphome-web-7d2a20_logs.txt](https://github.com/user-attachments/files/17849404/logs_esphome-web-7d2a20_logs.txt)

**Comment by sascha-egerer** [comment]
You should update to latest version. See #54

**Comment by skycryer** [comment]
OK wanted to avoid updating because everything else was working :D but after updating it shows correct, thank you.
