### ISSUE TITLE
[504] Adding VERDICHTERDREHZAHL as reading

### ISSUE THREAD

**Issue by zimbo86** [kr0ner/OneESP32ToRuleThemAll#71]
Hi,

i´m doing my first steps with this wonderful project and want to get rid of my fhem instance, which is currently only running to get data via usb from my thz504 and send it to HA..

So this is not an issue, furhermore a question how to handle it..

Stiebel removed the modbus pdf from their server, however i found a similar one on a third-party-website.
I´m currently optimizing my heatpump and want to measure "Verdichterdrehzahl" over time.

In Modbus configuration this is listed here:
![image](https://github.com/user-attachments/assets/c58f80db-79a5-43fe-ae43-eaae92043fd8)

Can you help me understand how to achieve this? I´m pretty new to the whole can-bus-thing, assuming it has to be added to settings.h
![image](https://github.com/user-attachments/assets/9d83715e-bdf8-4c00-9892-ace8ce530beb)

**Comment by kr0ner** [comment]
Hi @zimbo86. Glad you like the project. It is actually fairly easy to add a new property, once everything else is working:
All I did was to enter the pin, go to the menu of interest and look at the logs and match the 20Hz that were displayed
![image](https://github.com/user-attachments/assets/dbb6d1f1-1fe8-4c8b-8a08-eaec73f805d7)
The rest is copy paste as seen in https://github.com/kr0ner/OneESP32ToRuleThemAll/pull/72
Have fun :)
