### ISSUE TITLE
Wrong decimal interpretation in VERDICHTER HEIZLEISTUNG (. and ,)

### ISSUE THREAD

**Issue by zimbo86** [kr0ner/OneESP32ToRuleThemAll#79]
When VERDICHTER HEIZLEISTUNG contains decimal places, "." is not considerd as decimal marker
A value of 65,529 results in 65529 (65.529)

![image](https://github.com/user-attachments/assets/c14103e8-efc7-4844-bece-854eb9d67511)

**Comment by kr0ner** [comment]
That is a different issue. Values are supposed to be between 0 and 100 ... what you see is close to uint16_t::max().

**Comment by kr0ner** [comment]
looks like this is happening when hot water is being produced:
![image](https://github.com/user-attachments/assets/4acfe571-d785-4a1e-8aa3-0db8c096afb7)

For the rest of the time it is normal. Two ideas how to fix it ..
1, Ignore everything that is not a response .... https://github.com/kr0ner/OneESP32ToRuleThemAll/pull/77/commits/84f42e68dfb4df995257f4da51c60f1c2ed57a6e
2, Limit the value range of the sensor to [0,100] and drop values that are outside that range

I hope that 1, fixes it. Can you try that?

**Comment by kr0ner** [comment]
You still use day/night mode, right? Maybe that has an effect :shrug:

**Comment by zimbo86** [comment]
> You still use day/night mode, right? Maybe that has an effect 🤷

yes, but day for HC is 10-24:00, Hot Water 10-11:30 and 17:30-20:30

**Comment by kr0ner** [comment]
Ok, got it ... it is not "Heizleistung" but "Heizleistung relativ" ... which already states that values can be negative, too.
Fix therefore is:
![image](https://github.com/user-attachments/assets/1ddf7cb2-1fb5-4ac7-8797-1d285e7ea6c3)

**Comment by zimbo86** [comment]
perfect!
as value turns positiv at 18:00 Uhr this matches exactly.
![image](https://github.com/user-attachments/assets/cfdddb9d-faee-4134-b9e1-acae9027220c)

**Comment by zimbo86** [comment]
works like a charm
![image](https://github.com/user-attachments/assets/eaf0ad11-2c28-435e-a842-abecb88eb5cd)
