### ISSUE TITLE
PUMPENDREHZAHL_HEIZEN changes are not applied

### ISSUE THREAD

**Issue by sg-media-dev** [kr0ner/OneESP32ToRuleThemAll#8]
Hey kr0ner, the project is developing nicely - it's great. I have implemented the changes from #5 . The value RAUMEINFLUSS is displayed correctly and can be changed successfully. The correct value is also displayed for PUMPENDREHZAHL_HEIZEN, but the changes are not applied in the WP (THZ404). Do you have any ideas?

**Comment by kr0ner** [comment]
Hi @sg-media-dev. Could be, that the target is wrong and has to be adapted for the 404 case. You could try for example 

> PUMPENDREHZAHL_HEIZEN:          !include { file: thz504_number.yaml, vars: { property: "PUMPENDREHZAHL_HEIZEN"      , step:   "0.1", target: "HK1" }}

Can you compile with verbose logging and look for the messages that are being sent by the WP, when you adjust the settings there?
Weird, that it only works for one of them and for the other not 🤷

**Comment by sg-media-dev** [comment]
I no longer get a value with HK1. Well, that's not so important, but still strange ;)
