### ISSUE TITLE
FUSSPUNKT and STEIGUNG / added parameters, must be pulled manually

### ISSUE THREAD

**Issue by zimbo86** [kr0ner/OneESP32ToRuleThemAll#81]
I added FUSSPUNKT and STEIGUNG HK1, however these parameters wont pull automatically and need to be pulled

wp_base.yaml
```  
STEIGUNG_HK1:                   !include { file: wp_number.yaml, vars: { property: "STEIGUNG_HK1"               , min: "0", max: "5.0", step: "0.01", icon: "mdi:chart-bell-curve-cumulative"}}
FUSSPUNKT_HK1:                  !include { file: wp_number.yaml, vars: { property: "FUSSPUNKT_HK1"               , min: "0", max: "20", step: "0.1", icon: "mdi:download-outline"}}
```

property.h
```
PROPERTY(FUSSPUNKT_HK1, 0x059e, Type::et_dec_val);
PROPERTY(STEIGUNG_HK1, 0x010e, Type::et_dec_val);
```

**Comment by kr0ner** [comment]
They are related to HK1 so they should also have ```target: "HK1"```.
Number values are requested once at boot and after that, since they need to actively be changed, on reception. Maybe that is related to 
```
if (!isResponse(msg))
```
and that was broken recently ... in this case the following should fix it
```
    if (isRequest(msg)) {
        return {Property::kINDEX_NOT_FOUND, value};
    }
```

**Comment by kr0ner** [comment]
Did you add HK1 as target?
```
STEIGUNG_HK1:                   !include { file: wp_number.yaml, vars: { property: "STEIGUNG_HK1"               , min: "0", max: "5.0", step: "0.01", icon: "mdi:chart-bell-curve-cumulative", target: "HK1"}}
FUSSPUNKT_HK1:                  !include { file: wp_number.yaml, vars: { property: "FUSSPUNKT_HK1"               , min: "0", max: "20", step: "0.1", icon: "mdi:download-outline", target: "HK1"}}
```

**Comment by zimbo86** [comment]
nope, I didnt. Your response time is pure madness :D

**Comment by zimbo86** [comment]
that was the missing point, works!

![image](https://github.com/user-attachments/assets/72cf40e3-f5b8-457b-ae64-ba5139dc5571)
(I use differnet names)

**Comment by kr0ner** [comment]
try ```Type::et_cent_val``` instead of ```Type::et_dec_val```
```
PROPERTY(STEIGUNG_HK1, 0x010e, Type::et_cent_val);
```

**Comment by zimbo86** [comment]
that worked!

![image](https://github.com/user-attachments/assets/34f9d442-6724-4b27-9631-d63c8e1e4189)
